#![forbid(unsafe_code)]

use std::{fs, path::PathBuf};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use clarity_protocol::{
    ApiError, ClientMessage, CreateRoomRequest, CreateRoomResponse, ErrorCode, IceConfiguration,
    IceServer, PeerRole, PeerSnapshot, ProtocolInfo, RoomAccessPolicy, RoomLifecycle, RoomSnapshot,
    ServerMessage, SharingState, ViewerState,
};
use schemars::schema_for;
use ts_rs::TS;

#[derive(Debug, Parser)]
#[command(name = "clarity-xtask")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Export authoritative TypeScript declarations and JSON schemas.
    ExportProtocol,
}

fn main() -> Result<()> {
    match Cli::parse().command {
        Command::ExportProtocol => export_protocol(),
    }
}

fn export_protocol() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../web/src/generated");
    fs::create_dir_all(&root).context("create generated protocol directory")?;

    let declarations = [
        ProtocolInfo::decl(),
        PeerRole::decl(),
        RoomLifecycle::decl(),
        SharingState::decl(),
        RoomAccessPolicy::decl(),
        ViewerState::decl(),
        ErrorCode::decl(),
        CreateRoomRequest::decl(),
        CreateRoomResponse::decl(),
        ApiError::decl(),
        IceServer::decl(),
        IceConfiguration::decl(),
        PeerSnapshot::decl(),
        RoomSnapshot::decl(),
        ClientMessage::decl(),
        ServerMessage::decl(),
    ]
    .map(|declaration| format!("export {declaration}"))
    .join("\n\n");

    let typescript = format!(
        "// @generated by `cargo run -p clarity-xtask -- export-protocol`.\n// Do not edit manually.\n\n{declarations}\n"
    );
    fs::write(root.join("protocol.ts"), typescript).context("write TypeScript protocol")?;

    write_schema::<ClientMessage>(&root, "client-message.schema.json")?;
    write_schema::<ServerMessage>(&root, "server-message.schema.json")?;
    write_schema::<CreateRoomRequest>(&root, "create-room-request.schema.json")?;
    write_schema::<CreateRoomResponse>(&root, "create-room-response.schema.json")?;

    println!("exported protocol artifacts to {}", root.display());
    Ok(())
}

fn write_schema<T: schemars::JsonSchema>(directory: &std::path::Path, name: &str) -> Result<()> {
    let schema = schema_for!(T);
    let json = serde_json::to_string_pretty(&schema).context("serialize JSON schema")?;
    fs::write(directory.join(name), format!("{json}\n")).context("write JSON schema")
}
