// The browser-local identity: an Ed25519 key pair generated by WebCrypto. The
// private key is a non-extractable CryptoKey persisted in IndexedDB, so it can
// sign challenges but never leave this browser profile. The names the user
// presents to friends live in localStorage beside it.

import type { ExternalStateStore } from '@/hooks/use-session-state';
import { friendCodeForPublicKey } from './friend-code';

export type IdentityStatus = 'loading' | 'unsupported' | 'absent' | 'ready';

export interface IdentityState {
  status: IdentityStatus;
  friendCode: string | null;
  publicKeyBase64: string | null;
  displayName: string;
  deviceLabel: string;
  createdAt: number | null;
}

export interface StoredIdentityKeys {
  privateKey: CryptoKey;
  publicKeyRaw: ArrayBuffer;
  createdAt: number;
}

export interface IdentityKeyStorage {
  load(): Promise<StoredIdentityKeys | null>;
  save(keys: StoredIdentityKeys): Promise<void>;
}

const identityKeys = {
  displayName: 'clarity:identity:display-name',
  deviceLabel: 'clarity:identity:device-label',
} as const;

interface IdentityStoreOptions {
  keys?: IdentityKeyStorage;
  storage?: Pick<Storage, 'getItem' | 'setItem' | 'removeItem'>;
  subtle?: SubtleCrypto;
}

export class IdentityStore implements ExternalStateStore<IdentityState> {
  readonly #listeners = new Set<() => void>();
  readonly #keys: IdentityKeyStorage;
  readonly #storage: Pick<Storage, 'getItem' | 'setItem' | 'removeItem'>;
  readonly #subtle: SubtleCrypto | undefined;
  #privateKey: CryptoKey | null = null;
  #loading: Promise<void> | null = null;
  #state: IdentityState;

  public constructor(options: IdentityStoreOptions = {}) {
    this.#keys = options.keys ?? new IndexedDbKeyStorage();
    this.#storage = options.storage ?? window.localStorage;
    this.#subtle = options.subtle ?? globalThis.crypto?.subtle;
    this.#state = {
      status: 'loading',
      friendCode: null,
      publicKeyBase64: null,
      displayName: this.#storage.getItem(identityKeys.displayName) ?? '',
      deviceLabel: this.#storage.getItem(identityKeys.deviceLabel) ?? 'This browser',
      createdAt: null,
    };
  }

  public getSnapshot = (): IdentityState => this.#state;

  public subscribe = (listener: () => void): (() => void) => {
    this.#listeners.add(listener);
    return () => this.#listeners.delete(listener);
  };

  /** Loads the persisted identity, if any. Safe to call repeatedly. */
  public load(): Promise<void> {
    this.#loading ??= this.#load();
    return this.#loading;
  }

  /** Generates a fresh identity for this browser, replacing any existing one. */
  public async create(displayName: string, deviceLabel?: string): Promise<void> {
    if (!this.#subtle) {
      this.#patch({ status: 'unsupported' });
      throw new Error('This browser cannot create an identity key.');
    }
    let pair: CryptoKeyPair;
    try {
      pair = await this.#subtle.generateKey({ name: 'Ed25519' }, false, [
        'sign',
        'verify',
      ]);
    } catch {
      this.#patch({ status: 'unsupported' });
      throw new Error('This browser cannot create an Ed25519 identity key.');
    }
    const publicKeyRaw = await this.#subtle.exportKey('raw', pair.publicKey);
    const createdAt = Date.now();
    await this.#keys.save({ privateKey: pair.privateKey, publicKeyRaw, createdAt });
    this.setDisplayName(displayName);
    if (deviceLabel !== undefined) this.setDeviceLabel(deviceLabel);
    await this.#adopt(pair.privateKey, publicKeyRaw, createdAt);
  }

  /** Generates a new key pair, invalidating the old friend code. Names stay. */
  public async rotate(): Promise<void> {
    await this.create(this.#state.displayName, this.#state.deviceLabel);
  }

  /** Signs `message` with the identity's private key (64-byte Ed25519). */
  public async sign(message: Uint8Array): Promise<Uint8Array> {
    if (!this.#privateKey || !this.#subtle) {
      throw new Error('No identity key is available to sign with.');
    }
    const signature = await this.#subtle.sign(
      'Ed25519',
      this.#privateKey,
      message.slice().buffer,
    );
    return new Uint8Array(signature);
  }

  public setDisplayName(displayName: string): void {
    const trimmed = displayName.trim();
    this.#storage.setItem(identityKeys.displayName, trimmed);
    this.#patch({ displayName: trimmed });
  }

  public setDeviceLabel(deviceLabel: string): void {
    const trimmed = deviceLabel.trim();
    this.#storage.setItem(identityKeys.deviceLabel, trimmed);
    this.#patch({ deviceLabel: trimmed });
  }

  async #load(): Promise<void> {
    if (!this.#subtle) {
      this.#patch({ status: 'unsupported' });
      return;
    }
    try {
      const stored = await this.#keys.load();
      if (!stored) {
        this.#patch({ status: (await this.#supportsEd25519()) ? 'absent' : 'unsupported' });
        return;
      }
      await this.#adopt(stored.privateKey, stored.publicKeyRaw, stored.createdAt);
    } catch {
      this.#patch({ status: (await this.#supportsEd25519()) ? 'absent' : 'unsupported' });
    }
  }

  async #supportsEd25519(): Promise<boolean> {
    try {
      await this.#subtle!.generateKey({ name: 'Ed25519' }, false, ['sign', 'verify']);
      return true;
    } catch {
      return false;
    }
  }

  async #adopt(
    privateKey: CryptoKey,
    publicKeyRaw: ArrayBuffer,
    createdAt: number,
  ): Promise<void> {
    const publicKey = new Uint8Array(publicKeyRaw);
    this.#privateKey = privateKey;
    this.#patch({
      status: 'ready',
      friendCode: await friendCodeForPublicKey(publicKey, this.#subtle),
      publicKeyBase64: bytesToBase64(publicKey),
      createdAt,
    });
  }

  #patch(patch: Partial<IdentityState>): void {
    this.#state = { ...this.#state, ...patch };
    this.#listeners.forEach((listener) => listener());
  }
}

export function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

const DATABASE_NAME = 'clarity-identity';
const STORE_NAME = 'identity';
const RECORD_KEY = 'local';

/** Persists the CryptoKey pair in IndexedDB via structured clone, keeping the
 * private key non-extractable. */
class IndexedDbKeyStorage implements IdentityKeyStorage {
  public async load(): Promise<StoredIdentityKeys | null> {
    const database = await this.#open();
    try {
      const record = await request<unknown>(
        database.transaction(STORE_NAME, 'readonly').objectStore(STORE_NAME).get(RECORD_KEY),
      );
      return isStoredIdentityKeys(record) ? record : null;
    } finally {
      database.close();
    }
  }

  public async save(keys: StoredIdentityKeys): Promise<void> {
    const database = await this.#open();
    try {
      await request(
        database.transaction(STORE_NAME, 'readwrite').objectStore(STORE_NAME).put(keys, RECORD_KEY),
      );
    } finally {
      database.close();
    }
  }

  #open(): Promise<IDBDatabase> {
    const open = window.indexedDB.open(DATABASE_NAME, 1);
    open.addEventListener('upgradeneeded', () => {
      if (!open.result.objectStoreNames.contains(STORE_NAME)) {
        open.result.createObjectStore(STORE_NAME);
      }
    });
    return request(open);
  }
}

function request<T>(source: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    source.addEventListener('success', () => resolve(source.result));
    source.addEventListener('error', () =>
      reject(source.error ?? new Error('The identity database request failed.')),
    );
  });
}

function isStoredIdentityKeys(value: unknown): value is StoredIdentityKeys {
  return (
    typeof value === 'object' &&
    value !== null &&
    'privateKey' in value &&
    'publicKeyRaw' in value &&
    'createdAt' in value
  );
}
